// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	book "sewabuku/features/book"

	mock "github.com/stretchr/testify/mock"
)

// BookData is an autogenerated mock type for the BookData type
type BookData struct {
	mock.Mock
}

// Add provides a mock function with given fields: userId, newBook
func (_m *BookData) Add(userId uint, newBook book.Core) (book.Core, error) {
	ret := _m.Called(userId, newBook)

	var r0 book.Core
	if rf, ok := ret.Get(0).(func(uint, book.Core) book.Core); ok {
		r0 = rf(userId, newBook)
	} else {
		r0 = ret.Get(0).(book.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, book.Core) error); ok {
		r1 = rf(userId, newBook)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AllBooks provides a mock function with given fields:
func (_m *BookData) AllBooks() ([]book.Core, error) {
	ret := _m.Called()

	var r0 []book.Core
	if rf, ok := ret.Get(0).(func() []book.Core); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]book.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BooksDetail provides a mock function with given fields: userId, bookId
func (_m *BookData) BooksDetail(userId uint, bookId uint) (book.Core, error) {
	ret := _m.Called(userId, bookId)

	var r0 book.Core
	if rf, ok := ret.Get(0).(func(uint, uint) book.Core); ok {
		r0 = rf(userId, bookId)
	} else {
		r0 = ret.Get(0).(book.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = rf(userId, bookId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BooksRented provides a mock function with given fields: userId
func (_m *BookData) BooksRented(userId uint) ([]book.Core, error) {
	ret := _m.Called(userId)

	var r0 []book.Core
	if rf, ok := ret.Get(0).(func(uint) []book.Core); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]book.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: userId, bookId
func (_m *BookData) Delete(userId uint, bookId uint) error {
	ret := _m.Called(userId, bookId)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(userId, bookId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MyBooks provides a mock function with given fields: userId
func (_m *BookData) MyBooks(userId uint) ([]book.Core, error) {
	ret := _m.Called(userId)

	var r0 []book.Core
	if rf, ok := ret.Get(0).(func(uint) []book.Core); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]book.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: userId, bookId, updateBook
func (_m *BookData) Update(userId uint, bookId uint, updateBook book.Core) (book.Core, error) {
	ret := _m.Called(userId, bookId, updateBook)

	var r0 book.Core
	if rf, ok := ret.Get(0).(func(uint, uint, book.Core) book.Core); ok {
		r0 = rf(userId, bookId, updateBook)
	} else {
		r0 = ret.Get(0).(book.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, uint, book.Core) error); ok {
		r1 = rf(userId, bookId, updateBook)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBookData interface {
	mock.TestingT
	Cleanup(func())
}

// NewBookData creates a new instance of BookData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBookData(t mockConstructorTestingTNewBookData) *BookData {
	mock := &BookData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
