// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	book "sewabuku/features/book"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"
)

// BookService is an autogenerated mock type for the BookService type
type BookService struct {
	mock.Mock
}

// Add provides a mock function with given fields: token, newBook, image
func (_m *BookService) Add(token interface{}, newBook book.Core, image *multipart.FileHeader) (book.Core, error) {
	ret := _m.Called(token, newBook, image)

	var r0 book.Core
	if rf, ok := ret.Get(0).(func(interface{}, book.Core, *multipart.FileHeader) book.Core); ok {
		r0 = rf(token, newBook, image)
	} else {
		r0 = ret.Get(0).(book.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, book.Core, *multipart.FileHeader) error); ok {
		r1 = rf(token, newBook, image)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AllBooks provides a mock function with given fields:
func (_m *BookService) AllBooks() ([]book.Core, error) {
	ret := _m.Called()

	var r0 []book.Core
	if rf, ok := ret.Get(0).(func() []book.Core); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]book.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BooksDetail provides a mock function with given fields: token, bookId
func (_m *BookService) BooksDetail(token interface{}, bookId uint) (book.Core, error) {
	ret := _m.Called(token, bookId)

	var r0 book.Core
	if rf, ok := ret.Get(0).(func(interface{}, uint) book.Core); ok {
		r0 = rf(token, bookId)
	} else {
		r0 = ret.Get(0).(book.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, uint) error); ok {
		r1 = rf(token, bookId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BooksRented provides a mock function with given fields: token
func (_m *BookService) BooksRented(token interface{}) ([]book.Core, error) {
	ret := _m.Called(token)

	var r0 []book.Core
	if rf, ok := ret.Get(0).(func(interface{}) []book.Core); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]book.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: token, bookId
func (_m *BookService) Delete(token interface{}, bookId uint) error {
	ret := _m.Called(token, bookId)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, uint) error); ok {
		r0 = rf(token, bookId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MyBooks provides a mock function with given fields: token
func (_m *BookService) MyBooks(token interface{}) ([]book.Core, error) {
	ret := _m.Called(token)

	var r0 []book.Core
	if rf, ok := ret.Get(0).(func(interface{}) []book.Core); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]book.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: token, bookId, updateBook, updateImage
func (_m *BookService) Update(token interface{}, bookId uint, updateBook book.Core, updateImage *multipart.FileHeader) (book.Core, error) {
	ret := _m.Called(token, bookId, updateBook, updateImage)

	var r0 book.Core
	if rf, ok := ret.Get(0).(func(interface{}, uint, book.Core, *multipart.FileHeader) book.Core); ok {
		r0 = rf(token, bookId, updateBook, updateImage)
	} else {
		r0 = ret.Get(0).(book.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}, uint, book.Core, *multipart.FileHeader) error); ok {
		r1 = rf(token, bookId, updateBook, updateImage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBookService interface {
	mock.TestingT
	Cleanup(func())
}

// NewBookService creates a new instance of BookService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBookService(t mockConstructorTestingTNewBookService) *BookService {
	mock := &BookService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
